#!/bin/sh

##########
# example for serial jobs
# to run the job, just execute:
#     qsub serial.qsub
##########


# change the workding directory to where you submitted the job
#$ -cwd

#$ -pe orte 4

# merge the standard error stream into the standard output stream instead of having two separate error and output streams
#$ -j y

# request bash shell as shell for job
#$ -S /bin/bash


export OMP_SCHEDULE=DYNAMIC
export OMP_NUM_THREADS=$NSLOTS


#
# print date and time
date
hostname
#cp $SGE_O_WORKDIR/* $TMPDIR
#cd $TMPDIR 
# Sleep for 20 seconds


file=curr-nst.dat
rm $file

a=20
#for i in {1..19}
for i in {20..300..20}
do 

 echo $i

 echo "\$plasmon barrier_e=0.d0, barrier_h=0.d0,eps_coup=0.1d0,mscoup=0.1d0,relax=0.1d0,nst=$i,eig(1)=-1.0,eig(2)=1.d0 \$end" >in.2

 cat in.nst in.2 > new.td

 ../../bin/negf-pt <new.td >out 

 curr1=$(grep ' current  through lead:  1 is' out |cut -c32-47)
 curr2=$(grep ' current2 through lead:  1 is' out |cut -c32-47)
 curr3=$(grep ' current  through lead:  2 is' out |cut -c32-47)
 curr4=$(grep ' current2 through lead:  2 is' out |cut -c32-47)
 curr5=$(grep ' current  through lead:  3 is' out |cut -c32-47)
 curr6=$(grep ' current2 through lead:  3 is' out |cut -c32-47)

 echo "$i $curr1  $curr2  $curr3  $curr4  $curr5  $curr6 " >> $file

done


#sleep 20
# print date and time again
date
