#!/bin/sh


##########
# example for serial jobs
# to run the job, just execute:
#     qsub serial.qsub
##########

#$ -pe orte 1


# change the workding directory to where you submitted the job
#$ -cwd
#$ -o err.out

# merge the standard error stream into the standard output stream instead of having two separate error and output streams
#$ -j y

# request bash shell as shell for job
#$ -S /bin/bash


export OMP_SCHEDULE=DYNAMIC
export OMP_NUM_THREADS=$NSLOTS

#
# print date and time
date
hostname
#cp $SGE_O_WORKDIR/* $TMPDIR
#cd $TMPDIR 



 ../../../bin/negf-pt <new.td >out.400 


# print date and time again
date
