#!/bin/sh

##########
# example for serial jobs
# to run the job, just execute:
#     qsub serial.qsub
##########


# change the workding directory to where you submitted the job
#$ -cwd

# merge the standard error stream into the standard output stream instead of having two separate error and output streams
#$ -j y

# request bash shell as shell for job
#$ -S /bin/bash


export OMP_SCHEDULE=DYNAMIC
export OMP_NUM_THREADS=$NSLOTS


#
# print date and time
date
hostname
#cp $SGE_O_WORKDIR/* $TMPDIR
#cd $TMPDIR 

# Sleep for 20 seconds
~/lodestar/wblpade_lop/bin/zhy_wblpade <in.td  > out.td
#~/lodestar/bin/ldstar_zhy_q5test <int.td  > out.td
#sleep 20

# print date and time again
date
