#!/bin/sh

##########
# example for serial jobs
# to run the job, just execute:
#     qsub serial.qsub
##########


# change the workding directory to where you submitted the job
#$ -cwd

# merge the standard error stream into the standard output stream instead of having two separate error and output streams
#$ -j y

# request bash shell as shell for job
#$ -S /bin/bash


export OMP_SCHEDULE=DYNAMIC
export OMP_NUM_THREADS=$NSLOTS


#
# print date and time
date
hostname
#cp $SGE_O_WORKDIR/* $TMPDIR
#cd $TMPDIR 
# Sleep for 20 seconds


file=curr-volt.dat
rm $file

a=0.02
for i in {0..60}
do 
 c=$(echo "$i*$a"|bc -l)
 volt=$(echo "2*$c"|bc -l)
 echo "ampl=-$c, ampr=$c \$end" > in.2 
 cat in.iv in.2 > new.td

 ../../bin/negf-pt <new.td >out 

 curr1=$(grep 'current through 1' out |cut -c26-41)
 curr2=$(grep 'current through 2' out |cut -c26-41)
 curr3=$(grep 'current through 3' out |cut -c26-41)

 echo "$volt $curr1  $curr2  $curr3 " >> $file

done


#sleep 20
# print date and time again
date
