#!/bin/sh

##########
# example for serial jobs
# to run the job, just execute:
#     qsub serial.qsub
##########


# change the workding directory to where you submitted the job
#$ -cwd

# merge the standard error stream into the standard output stream instead of having two separate error and output streams
#$ -j y
#$ -pe orte 8

# request bash shell as shell for job
#$ -S /bin/bash


export OMP_SCHEDULE=DYNAMIC
export OMP_NUM_THREADS=$NSLOTS


#
# print date and time
date
hostname
#cp $SGE_O_WORKDIR/* $TMPDIR
#cd $TMPDIR 
# Sleep for 20 seconds


file=curr-freq.dat
file2=flux.dat
rm $file $file2

a=0.02
for i in {1..250}
do 
 c=$(echo "$i*$a"|bc -l)
 echo "phfreq=$c, \$end" > in.2
 cat in.freq in.2 > new.td

 ../../bin/negf-pt <new.td >out 

 curr1=$(grep ' current  through lead:  1 is' out |cut -c32-47)
 curr2=$(grep ' current2 through lead:  1 is' out |cut -c32-47)
 curr3=$(grep ' current  through lead:  2 is' out |cut -c32-47)
 curr4=$(grep ' current2 through lead:  2 is' out |cut -c32-47)
 curr5=$(grep ' current  through lead:  3 is' out |cut -c32-47)
 curr6=$(grep ' current2 through lead:  3 is' out |cut -c32-47)

 echo "$c $curr1  $curr2  $curr3  $curr4  $curr5  $curr6 " >> $file

 flux=$(grep ' absorped photon flux is' out |cut -c27-42)
 maxcurr=$(grep ' maximum photocurrent is' out |cut -c27-42)
 IQE=$(grep ' IQE is  ' out |cut -c27-32)

 echo "$c $flux  $maxcurr  $IQE " >> $file2

done


#sleep 20
# print date and time again
date
